swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  - https
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User accounts API
      description: User bank account list retrieval API
      #produces:
       # - application/json
      responses:
        '200':
          description: user bank accounts successfully recovered
          schema:
            $ref: '#/definitions/UserAccounts'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/accounts/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API transactions of a users bank account
      description: User bank account transaction list retrieval API
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          schema:
            type: string
      responses:
        '200':
          description: User bank account transactions successfully recovered
          schema:
            $ref: '#/definitions/UserAccountTransactions'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error 
  /user/accounts/{accountID}/transactions/{transactionID}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Category of a Transaction
      description: Update the category of a user's bank account transaction using transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          schema:
            type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's bank account transaction
          schema:
            type: string
        - in: body
          name: body
          description: Category Payload
          required: true
          schema:
            $ref: '#/definitions/Category'
            produces:
              - application/json
      responses:
        '200':
          description: User bank account transaction category successfully updated
          schema:
            $ref: '#/definitions/UserAccountTransactionCategory'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error


  /user/accounts/{accountID}/transactions/{transactionID}/note:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add Note for a Transaction
      description: Add the note of a user's bank account transaction using transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          schema:
            type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's bank account transaction
          schema:
            type: string
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/Note'
            produces:
              - application/json
      responses:
        '200':
          description: User bank account transaction note successfully added
          schema:
            $ref: '#/definitions/UserAccountTransactionNote'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error 
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Note for a Transaction
      description: Update the note of a user's bank account transaction using transactionID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          schema:
            type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's bank account transaction
          schema:
            type: string
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/Note'
            produces:
              - application/json
      responses:
        '200':
          description: User bank account transaction note successfully updated
          schema:
            $ref: '#/definitions/UserAccountTransactionNote'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error 
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete a Transaction
      description: Remove transaction note from a user's bank account using transaction ID
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID of the user's bank account
          schema:
            type: string
        - name: transactionID
          in: path
          required: true
          description: ID of the user's bank account transaction
          schema:
            type: string
      responses:
        '204':
          description: Transaction deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error         
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccounts:
    type: object
    properties:
      message:
        type: string
      body:
        type: object
        properties:
          accounts:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                amount:
                  type: string
                description:
                  type: string
            minItems: 3
            maxItems: 3
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      transaction_type:
        type: string
      category:
        type: string
      note:
        type: string
  UserAccountTransactions:
    type: object
    properties:
      message:
        type: string
      body:
        type: object
        properties:
          account:
            type: array
            items:
              $ref: '#/definitions/Transaction'
            minItems: 3  
  UserAccountTransactionCategory:
    type: object
    properties:
      message:
        type: string
      body:
        type: object
        properties:
          account:
            type: object
            properties:
              transaction:
                type: object
                properties:
                  transactionID:
                    type: string
                  category:
                    type: string
  Category:
    properties:
      category:
        type: string
        description: transaction category              
  UserAccountTransactionNote:
    type: object
    properties:
      message:
        type: string
      body:
        type: object
        properties:
          account:
            type: object
            properties:
              transaction:
                type: object
                properties:
                  transactionID:
                    type: string
                  note:
                    type: string
  Note:
    properties:
      note:
        type: string
        description: transaction note 
                                       
                  

                    